In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [6]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [7]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [9]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [10]:
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [11]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4 , verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 3s 268ms/step - accuracy: 0.5000 - loss: 0.6940 - val_accuracy: 0.2500 - val_loss: 0.7443
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.6924 - val_accuracy: 0.2500 - val_loss: 0.7430
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.6910 - val_accuracy: 0.2500 - val_loss: 0.7417
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.6892 - val_accuracy: 0.2500 - val_loss: 0.7404
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5833 - loss: 0.6875 - val_accuracy: 0.2500 - val_loss: 0.7392
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6667 - loss: 0.6857 - val_accuracy: 0.2500 - val_loss: 0.7378
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.6667 - loss: 0.6840 - val_accuracy: 0.2500 - val_loss: 0.7358
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6667 - loss: 0.6826 - val_accuracy: 0.2500 - val_loss: 0.7338
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6807 - val_accuracy: 0.2500 - val_loss: 0.7319
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6667 - loss: 0.6794 - val_accuracy: 0.2500 - val_loss: 0.7299
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6667 - loss: 0.6778 - val_accuracy: 0.2500 - val_loss: 0.7279
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6760 - val_accuracy: 0.2500 - val_loss: 0.7258
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6739 - val_accuracy: 0.2500 - val_loss: 0.7237
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6714 - val_accuracy: 0.2500 - val_loss: 0.7216
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6667 - loss: 0.6695 - val_accuracy: 0.2500 - val_loss: 0.7194
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6667 - loss: 0.6671 - val_accuracy: 0.2500 - val_loss: 0.7173
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6667 - loss: 0.6644 - val_accuracy: 0.2500 - val_loss: 0.7150
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6619 - val_accuracy: 0.2500 - val_loss: 0.7127
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6667 - loss: 0.6589 - val_accuracy: 0.2500 - val_loss: 0.7105
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6667 - loss: 0.6558 - val_accuracy: 0.2500 - val_loss: 0.7083
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.6667 - loss: 0.6529 - val_accuracy: 0.2500 - val_loss: 0.7058
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7500 - loss: 0.6499 - val_accuracy: 0.2500 - val_loss: 0.7033
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7500 - loss: 0.6473 - val_accuracy: 0.5000 - val_loss: 0.7009
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.7500 - loss: 0.6450 - val_accuracy: 0.5000 - val_loss: 0.6986
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8333 - loss: 0.6424 - val_accuracy: 0.5000 - val_loss: 0.6965
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.8333 - loss: 0.6401 - val_accuracy: 0.5000 - val_loss: 0.6943
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8333 - loss: 0.6380 - val_accuracy: 0.5000 - val_loss: 0.6922
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.8333 - loss: 0.6359 - val_accuracy: 0.7500 - val_loss: 0.6902
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.8333 - loss: 0.6340 - val_accuracy: 0.7500 - val_loss: 0.6882
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.8333 - loss: 0.6320 - val_accuracy: 0.7500 - val_loss: 0.6864
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8333 - loss: 0.6301 - val_accuracy: 0.7500 - val_loss: 0.6845
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.8333 - loss: 0.6291 - val_accuracy: 0.7500 - val_loss: 0.6825
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.9167 - loss: 0.6269 - val_accuracy: 0.7500 - val_loss: 0.6808
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.6256 - val_accuracy: 0.7500 - val_loss: 0.6790
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9167 - loss: 0.6238 - val_accuracy: 0.7500 - val_loss: 0.6776
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9167 - loss: 0.6224 - val_accuracy: 0.7500 - val_loss: 0.6760
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.9167 - loss: 0.6214 - val_accuracy: 0.7500 - val_loss: 0.6743
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9167 - loss: 0.6196 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.6183 - val_accuracy: 0.7500 - val_loss: 0.6714
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.6172 - val_accuracy: 0.7500 - val_loss: 0.6700
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9167 - loss: 0.6159 - val_accuracy: 1.0000 - val_loss: 0.6685
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.6148 - val_accuracy: 1.0000 - val_loss: 0.6670
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 1.0000 - loss: 0.6135 - val_accuracy: 1.0000 - val_loss: 0.6657
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.6125 - val_accuracy: 1.0000 - val_loss: 0.6644
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.6115 - val_accuracy: 1.0000 - val_loss: 0.6631
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.6103 - val_accuracy: 1.0000 - val_loss: 0.6619
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 1.0000 - loss: 0.6094 - val_accuracy: 1.0000 - val_loss: 0.6606
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.6084 - val_accuracy: 1.0000 - val_loss: 0.6593
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.6074 - val_accuracy: 1.0000 - val_loss: 0.6581
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.6063 - val_accuracy: 1.0000 - val_loss: 0.6569
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.6053 - val_accuracy: 1.0000 - val_loss: 0.6557
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 1.0000 - loss: 0.6045 - val_accuracy: 1.0000 - val_loss: 0.6545
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.6034 - val_accuracy: 1.0000 - val_loss: 0.6534
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.6025 - val_accuracy: 1.0000 - val_loss: 0.6523
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.6017 - val_accuracy: 1.0000 - val_loss: 0.6511
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 1.0000 - loss: 0.6005 - val_accuracy: 1.0000 - val_loss: 0.6500
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.5998 - val_accuracy: 1.0000 - val_loss: 0.6488
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.5990 - val_accuracy: 1.0000 - val_loss: 0.6476
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5980 - val_accuracy: 1.0000 - val_loss: 0.6464
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.5971 - val_accuracy: 1.0000 - val_loss: 0.6453
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.5960 - val_accuracy: 1.0000 - val_loss: 0.6442
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.5951 - val_accuracy: 1.0000 - val_loss: 0.6433
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.5943 - val_accuracy: 1.0000 - val_loss: 0.6423
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.5933 - val_accuracy: 1.0000 - val_loss: 0.6412
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.5925 - val_accuracy: 1.0000 - val_loss: 0.6402
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.5916 - val_accuracy: 1.0000 - val_loss: 0.6391
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.5907 - val_accuracy: 1.0000 - val_loss: 0.6379
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.5897 - val_accuracy: 1.0000 - val_loss: 0.6369
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.5890 - val_accuracy: 1.0000 - val_loss: 0.6358
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5879 - val_accuracy: 1.0000 - val_loss: 0.6349
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 1.0000 - loss: 0.5871 - val_accuracy: 1.0000 - val_loss: 0.6339
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.5861 - val_accuracy: 1.0000 - val_loss: 0.6328
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.5853 - val_accuracy: 1.0000 - val_loss: 0.6318
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5845 - val_accuracy: 1.0000 - val_loss: 0.6308
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5835 - val_accuracy: 1.0000 - val_loss: 0.6298
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 1.0000 - loss: 0.5826 - val_accuracy: 1.0000 - val_loss: 0.6287
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.5819 - val_accuracy: 1.0000 - val_loss: 0.6278
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.5809 - val_accuracy: 1.0000 - val_loss: 0.6268
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.5800 - val_accuracy: 1.0000 - val_loss: 0.6258
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.5791 - val_accuracy: 1.0000 - val_loss: 0.6248
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.5782 - val_accuracy: 1.0000 - val_loss: 0.6239
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.5773 - val_accuracy: 1.0000 - val_loss: 0.6230
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 1.0000 - loss: 0.5765 - val_accuracy: 1.0000 - val_loss: 0.6220
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.9167 - loss: 0.5756 - val_accuracy: 1.0000 - val_loss: 0.6210
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.9167 - loss: 0.5748 - val_accuracy: 1.0000 - val_loss: 0.6201
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9167 - loss: 0.5744 - val_accuracy: 1.0000 - val_loss: 0.6190
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5730 - val_accuracy: 1.0000 - val_loss: 0.6182
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9167 - loss: 0.5723 - val_accuracy: 1.0000 - val_loss: 0.6173
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9167 - loss: 0.5715 - val_accuracy: 1.0000 - val_loss: 0.6163
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.9167 - loss: 0.5706 - val_accuracy: 1.0000 - val_loss: 0.6155
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.9167 - loss: 0.5698 - val_accuracy: 1.0000 - val_loss: 0.6146
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.9167 - loss: 0.5689 - val_accuracy: 1.0000 - val_loss: 0.6136
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.9167 - loss: 0.5681 - val_accuracy: 1.0000 - val_loss: 0.6127
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9167 - loss: 0.5672 - val_accuracy: 1.0000 - val_loss: 0.6118
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.9167 - loss: 0.5664 - val_accuracy: 1.0000 - val_loss: 0.6109
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.9167 - loss: 0.5655 - val_accuracy: 1.0000 - val_loss: 0.6100
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9167 - loss: 0.5647 - val_accuracy: 1.0000 - val_loss: 0.6090
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9167 - loss: 0.5642 - val_accuracy: 1.0000 - val_loss: 0.6080
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9167 - loss: 0.5630 - val_accuracy: 1.0000 - val_loss: 0.6071
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9167 - loss: 0.5621 - val_accuracy: 1.0000 - val_loss: 0.6062

In [12]:
from tensorflow.keras import optimizers

In [13]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)